name: urban_move
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.2
  flutter_map: ^7.0.2
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  assets: 
    - .env
    
  uses-material-design: true